"""
Data Structures for Algorithmic Trading Engine

Defines the core entities used throughout the trading system:
- Signal: what the model wants to do
- PositionState: what you currently hold
- ExecutionConfig: how trades should be executed
- OrderPlan: what we intend to send to market
- DecisionLogEntry: record of every decision made

These structures provide a clean interface between signal generation,
position management, and trade execution.
"""

from dataclasses import dataclass, field
from typing import Optional, Dict, Any, Literal
from datetime import datetime


@dataclass
class Signal:
    """
    Represents a trading signal generated by the forecasting model.
    
    Fields:
        symbol: ticker symbol (e.g., 'AAPL')
        signal_type: 'buy', 'sell', or 'hold'
        confidence: model confidence (0.0 to 1.0)
        prob_profit: probability of profit from ensemble forecast
        meta: additional signal metadata (RSI, Bollinger z-score, etc.)
    """
    symbol: str
    signal_type: Literal['buy', 'sell', 'hold']
    confidence: float
    prob_profit: float
    meta: Dict[str, Any] = field(default_factory=dict)
    
    def __post_init__(self):
        """Validate signal fields."""
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError(f"Confidence must be between 0 and 1, got {self.confidence}")
        if not 0.0 <= self.prob_profit <= 1.0:
            raise ValueError(f"Prob profit must be between 0 and 1, got {self.prob_profit}")
        self.signal_type = self.signal_type.lower()


@dataclass
class PositionState:
    """
    Represents current position in a single asset.
    
    Fields:
        symbol: ticker symbol
        quantity: number of shares (positive for long, negative for short, 0 for flat)
        avg_entry_price: average price paid for current position
        side: 'long', 'short', or 'flat'
        source: where this data came from ('alpaca' or 'sim')
        unrealized_pl: current unrealized profit/loss (optional)
    """
    symbol: str
    quantity: float
    avg_entry_price: float
    side: Literal['long', 'short', 'flat']
    source: Literal['alpaca', 'sim']
    unrealized_pl: Optional[float] = None
    
    def __post_init__(self):
        """Ensure side matches quantity sign."""
        if self.quantity > 0 and self.side != 'long':
            raise ValueError(f"Positive quantity requires side='long', got '{self.side}'")
        if self.quantity < 0 and self.side != 'short':
            raise ValueError(f"Negative quantity requires side='short', got '{self.side}'")
        if self.quantity == 0 and self.side != 'flat':
            self.side = 'flat'  # Auto-correct to flat


@dataclass
class ExecutionConfig:
    """
    Configuration for trade execution behavior.
    
    Fields:
        execution_mode: 'simulation', 'paper', or 'live'
        allow_short_selling: whether short positions are allowed
        dry_run: if True, log decisions but don't execute
        base_risk_pct: base risk per trade as % of account (e.g., 1.0 for 1%)
        tp_pct: take profit percentage (e.g., 0.04 for 4%)
        sl_pct: stop loss percentage (e.g., 0.02 for 2%)
        max_position_pct_of_equity: max position size as % of portfolio (e.g., 20.0 for 20%)
        min_confidence: minimum confidence threshold to trade
        min_prob_up: minimum probability of profit to trade
    """
    execution_mode: Literal['simulation', 'paper', 'live']
    allow_short_selling: bool = False
    dry_run: bool = True
    base_risk_pct: float = 1.0
    tp_pct: float = 0.04
    sl_pct: float = 0.02
    max_position_pct_of_equity: float = 20.0
    min_confidence: float = 0.50
    min_prob_up: float = 0.50


@dataclass
class TradingSystem:
    """
    Bundles system-level dependencies to reduce parameter passing.

    Instead of threading alpaca_client through every function call,
    pass a TradingSystem instance. Supports future multi-broker architectures
    where alpaca_client could be swapped for any broker implementation.

    Fields:
        config: execution configuration (mode, risk params, thresholds)
        alpaca_client: live/paper broker client, or None for simulation
    """
    config: ExecutionConfig
    alpaca_client: Optional[Any] = None


@dataclass
class OrderPlan:
    """
    A concrete plan for an order to submit to the broker or simulation.
    
    Fields:
        symbol: ticker symbol
        side: 'buy' or 'sell'
        quantity: number of shares to trade
        entry_type: 'market' or 'limit'
        limit_price: limit price if entry_type='limit'
        tp_price: take profit price (optional, for bracket orders)
        sl_price: stop loss price (optional, for bracket orders)
        time_in_force: 'day', 'gtc', etc.
        reason: human-readable explanation linking back to signal
    """
    symbol: str
    side: Literal['buy', 'sell']
    quantity: int
    entry_type: Literal['market', 'limit']
    limit_price: Optional[float] = None
    tp_price: Optional[float] = None
    sl_price: Optional[float] = None
    time_in_force: str = 'day'
    reason: str = ''
    
    def has_bracket(self) -> bool:
        """Check if this order has both TP and SL for bracket execution."""
        return self.tp_price is not None and self.sl_price is not None


@dataclass
class DecisionLogEntry:
    """
    Complete record of a single trading decision.
    
    Captures inputs (signal, position state), decision (action, reason),
    and execution result (success, order ID, timestamps).
    """
    # Inputs
    timestamp: datetime
    symbol: str
    signal_type: str
    confidence: float
    prob_profit: float
    position_quantity_before: float
    position_side_before: str
    execution_mode: str
    
    # Decision
    action: Literal['buy', 'sell', 'hold', 'rejected']
    reason: str
    
    # Order details (if action was buy/sell)
    planned_quantity: Optional[int] = None
    planned_entry_price: Optional[float] = None
    planned_tp_price: Optional[float] = None
    planned_sl_price: Optional[float] = None
    
    # Execution result
    executed: bool = False
    broker_order_id: Optional[str] = None
    execution_timestamp: Optional[datetime] = None
    error_message: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for CSV/JSON serialization."""
        return {
            'timestamp': self.timestamp.isoformat(),
            'symbol': self.symbol,
            'signal_type': self.signal_type,
            'confidence': self.confidence,
            'prob_profit': self.prob_profit,
            'position_quantity_before': self.position_quantity_before,
            'position_side_before': self.position_side_before,
            'execution_mode': self.execution_mode,
            'action': self.action,
            'reason': self.reason,
            'planned_quantity': self.planned_quantity,
            'planned_entry_price': self.planned_entry_price,
            'planned_tp_price': self.planned_tp_price,
            'planned_sl_price': self.planned_sl_price,
            'executed': self.executed,
            'broker_order_id': self.broker_order_id,
            'execution_timestamp': self.execution_timestamp.isoformat() if self.execution_timestamp else None,
            'error_message': self.error_message
        }
