"""
Data Structures for Algorithmic Trading Engine

Defines the core entities used throughout the trading system:
- Signal: what the model wants to do
- PositionState: what you currently hold
- ExecutionConfig: how trades should be executed
- OrderPlan: what we intend to send to market
- DecisionLogEntry: record of every decision made

These structures provide a clean interface between signal generation,
position management, and trade execution.
"""

from dataclasses import dataclass, field, asdict
from typing import Optional, Dict, Any, List, Literal, Mapping, cast
from datetime import datetime
import json


@dataclass
class Signal:
    """
    Represents a trading signal generated by the forecasting model.
    
    Fields:
        symbol: ticker symbol (e.g., 'AAPL')
        signal_type: 'buy', 'sell', or 'hold'
        confidence: model confidence (0.0 to 1.0)
        prob_profit: probability of profit from ensemble forecast
        type_beliefs: posterior beliefs over market types (sums to 1 when present)
        meta: additional signal metadata (RSI, Bollinger z-score, etc.)
    """
    symbol: str
    signal_type: Literal['buy', 'sell', 'hold']
    confidence: float
    prob_profit: float
    type_beliefs: Dict[str, float] = field(default_factory=dict)
    meta: Dict[str, Any] = field(default_factory=dict)
    
    def __post_init__(self):
        """Validate signal fields."""
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError(f"Confidence must be between 0 and 1, got {self.confidence}")
        if not 0.0 <= self.prob_profit <= 1.0:
            raise ValueError(f"Prob profit must be between 0 and 1, got {self.prob_profit}")
        normalized_signal_type = str(self.signal_type).lower()
        if normalized_signal_type not in {'buy', 'sell', 'hold'}:
            raise ValueError(f"Signal type must be buy/sell/hold, got {self.signal_type}")
        self.signal_type = cast(Literal['buy', 'sell', 'hold'], normalized_signal_type)

        if self.type_beliefs:
            clipped = {k: max(0.0, float(v)) for k, v in self.type_beliefs.items()}
            total = sum(clipped.values())
            if total > 0.0:
                self.type_beliefs = {k: v / total for k, v in clipped.items()}
            else:
                self.type_beliefs = {}


@dataclass
class PositionState:
    """
    Represents current position in a single asset.
    
    Fields:
        symbol: ticker symbol
        quantity: number of shares (positive for long, negative for short, 0 for flat)
        avg_entry_price: average price paid for current position
        side: 'long', 'short', or 'flat'
        source: where this data came from ('alpaca', 'paper', or 'sim')
        unrealized_pl: current unrealized profit/loss (optional)
    """
    symbol: str
    quantity: float
    avg_entry_price: float
    side: Literal['long', 'short', 'flat']
    source: Literal['alpaca', 'paper', 'sim']
    unrealized_pl: Optional[float] = None
    
    def __post_init__(self):
        """Ensure side matches quantity sign."""
        if self.quantity > 0 and self.side != 'long':
            raise ValueError(f"Positive quantity requires side='long', got '{self.side}'")
        if self.quantity < 0 and self.side != 'short':
            raise ValueError(f"Negative quantity requires side='short', got '{self.side}'")
        if self.quantity == 0 and self.side != 'flat':
            self.side = 'flat'  # Auto-correct to flat


@dataclass
class ExecutionConfig:
    """
    Configuration for trade execution behavior.
    
    Fields:
        execution_mode: 'simulation', 'paper', or 'live'
        allow_short_selling: whether short positions are allowed
        dry_run: if True, log decisions but don't execute
        base_risk_pct: base risk per trade as % of account (e.g., 1.0 for 1%)
        tp_pct: take profit percentage (e.g., 0.04 for 4%)
        sl_pct: stop loss percentage (e.g., 0.02 for 2%)
        max_position_pct_of_equity: max position size as % of portfolio (e.g., 20.0 for 20%)
        min_confidence: minimum confidence threshold to trade
        min_prob_up: minimum probability of profit to trade
    """
    execution_mode: Literal['simulation', 'paper', 'live']
    allow_short_selling: bool = False
    dry_run: bool = True
    base_risk_pct: float = 1.0
    tp_pct: float = 0.04
    sl_pct: float = 0.02
    max_position_pct_of_equity: float = 20.0
    min_confidence: float = 0.50
    min_prob_up: float = 0.50
    enforce_safety_veto: bool = True
    max_allowed_drawdown_pct: Optional[float] = None
    asset_scope: Literal['us_equities', 'multi_asset'] = 'us_equities'

    # Benchmark freeze controls (Phase 0)
    benchmark_bundle_name: Optional[str] = None
    benchmark_seed: Optional[int] = None
    benchmark_config_snapshot_path: Optional[str] = None

    # Stochastic dynamics controls (Milestone 1)
    shock_distribution: Literal['normal', 'alpha_stable'] = 'normal'
    enable_fat_tail_mode: bool = False
    stable_alpha: Optional[float] = None
    stable_beta: Optional[float] = None
    stable_scale: Optional[float] = None
    stable_loc: Optional[float] = None

    # Uncertainty gate rollout controls (Milestone 2 scaffolding)
    uncertainty_gate_mode: Literal['off', 'shadow', 'enforce'] = 'off'
    max_belief_entropy: Optional[float] = None
    max_kl_divergence: Optional[float] = None

    def to_dict(self) -> Dict[str, Any]:
        """Serialize config so benchmark snapshots are easy to freeze to disk."""
        return asdict(self)


@dataclass
class TradingSystem:
    """
    Bundles system-level dependencies to reduce parameter passing.

    Instead of threading alpaca_client through every function call,
    pass a TradingSystem instance. Supports future multi-broker architectures
    where alpaca_client could be swapped for any broker implementation.

    Fields:
        config: execution configuration (mode, risk params, thresholds)
        alpaca_client: live/paper broker client, or None for simulation
    """
    config: ExecutionConfig
    alpaca_client: Optional[Any] = None


@dataclass
class OrderPlan:
    """
    A concrete plan for an order to submit to the broker or simulation.
    
    Fields:
        symbol: ticker symbol
        side: 'buy' or 'sell'
        quantity: number of shares to trade
        entry_type: 'market' or 'limit'
        limit_price: limit price if entry_type='limit'
        tp_price: take profit price (optional, for bracket orders)
        sl_price: stop loss price (optional, for bracket orders)
        time_in_force: 'day', 'gtc', etc.
        reason: human-readable explanation linking back to signal
    """
    symbol: str
    side: Literal['buy', 'sell']
    quantity: int
    entry_type: Literal['market', 'limit']
    limit_price: Optional[float] = None
    tp_price: Optional[float] = None
    sl_price: Optional[float] = None
    time_in_force: str = 'day'
    reason: str = ''
    
    def has_bracket(self) -> bool:
        """Check if this order has both TP and SL for bracket execution."""
        return self.tp_price is not None and self.sl_price is not None


@dataclass
class DecisionLogEntry:
    """
    Complete record of a single trading decision.
    
    Captures inputs (signal, position state), decision (action, reason),
    and execution result (success, order ID, timestamps).
    """
    # Inputs
    timestamp: datetime
    symbol: str
    signal_type: str
    confidence: float
    prob_profit: float
    position_quantity_before: float
    position_side_before: str
    execution_mode: str
    
    # Decision
    action: Literal['buy', 'sell', 'hold', 'rejected']
    reason: str
    
    # Order details (if action was buy/sell)
    planned_quantity: Optional[int] = None
    planned_entry_price: Optional[float] = None
    planned_tp_price: Optional[float] = None
    planned_sl_price: Optional[float] = None
    
    # Execution result
    executed: bool = False
    broker_order_id: Optional[str] = None
    execution_timestamp: Optional[datetime] = None
    error_message: Optional[str] = None

    # Optional diagnostics (backward-compatible)
    belief_entropy: Optional[float] = None
    kl_divergence: Optional[float] = None
    uncertainty_veto_flag: Optional[bool] = None
    uncertainty_veto_reason: Optional[str] = None
    tail_cvar_estimate: Optional[float] = None
    simulated_crash_freq_3sigma: Optional[float] = None
    simulated_crash_freq_5sigma: Optional[float] = None
    simulated_crash_freq_10sigma: Optional[float] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for CSV/JSON serialization."""
        return {
            'timestamp': self.timestamp.isoformat(),
            'symbol': self.symbol,
            'signal_type': self.signal_type,
            'confidence': self.confidence,
            'prob_profit': self.prob_profit,
            'position_quantity_before': self.position_quantity_before,
            'position_side_before': self.position_side_before,
            'execution_mode': self.execution_mode,
            'action': self.action,
            'reason': self.reason,
            'planned_quantity': self.planned_quantity,
            'planned_entry_price': self.planned_entry_price,
            'planned_tp_price': self.planned_tp_price,
            'planned_sl_price': self.planned_sl_price,
            'executed': self.executed,
            'broker_order_id': self.broker_order_id,
            'execution_timestamp': self.execution_timestamp.isoformat() if self.execution_timestamp else None,
            'error_message': self.error_message,
            'belief_entropy': self.belief_entropy,
            'kl_divergence': self.kl_divergence,
            'uncertainty_veto_flag': self.uncertainty_veto_flag,
            'uncertainty_veto_reason': self.uncertainty_veto_reason,
            'tail_cvar_estimate': self.tail_cvar_estimate,
            'simulated_crash_freq_3sigma': self.simulated_crash_freq_3sigma,
            'simulated_crash_freq_5sigma': self.simulated_crash_freq_5sigma,
            'simulated_crash_freq_10sigma': self.simulated_crash_freq_10sigma,
        }


@dataclass
class RLObservation:
    """RL-friendly observation container for hybrid technical + Bayesian features."""
    symbol: str
    timestamp: datetime
    features: Dict[str, float]
    minutes_to_close: Optional[float] = None

    def normalize_observation(
        self,
        feature_stats: Mapping[str, Mapping[str, float]],
        clip_abs: Optional[float] = 6.0,
    ) -> Dict[str, float]:
        """Z-score normalize observation values from provided train-set statistics."""
        normalized: Dict[str, float] = {}
        for name, raw_value in self.features.items():
            stats = feature_stats.get(name, {})
            mean = float(stats.get('mean', 0.0))
            std = float(stats.get('std', 1.0))
            if std <= 0.0:
                std = 1.0
            value = (float(raw_value) - mean) / std
            if clip_abs is not None:
                value = max(-clip_abs, min(clip_abs, value))
            normalized[name] = value
        if self.minutes_to_close is not None:
            normalized['minutes_to_close'] = float(self.minutes_to_close)
        return normalized

    def to_json(self) -> str:
        payload = {
            'symbol': self.symbol,
            'timestamp': self.timestamp.isoformat(),
            'features': self.features,
            'minutes_to_close': self.minutes_to_close,
        }
        return json.dumps(payload, sort_keys=True)


@dataclass
class RLExperience:
    """One offline RL transition tuple (S, A, R, S', done)."""
    episode_id: str
    symbol: str
    action_code: int
    reward_immediate: float
    done: bool
    state: Dict[str, Any]
    next_state: Optional[Dict[str, Any]] = None
    reward_risk_adjusted: Optional[float] = None
    instrument_type: str = 'equity'
    timestamp: Optional[datetime] = None
    account_id: Optional[str] = None
    trade_id: Optional[str] = None
    decision_id: Optional[int] = None
    time_to_close: Optional[float] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            'episode_id': self.episode_id,
            'symbol': self.symbol,
            'action_code': self.action_code,
            'reward_immediate': self.reward_immediate,
            'reward_risk_adjusted': self.reward_risk_adjusted,
            'done': self.done,
            'state': self.state,
            'next_state': self.next_state,
            'instrument_type': self.instrument_type,
            'timestamp': self.timestamp.isoformat() if self.timestamp else None,
            'account_id': self.account_id,
            'trade_id': self.trade_id,
            'decision_id': self.decision_id,
            'time_to_close': self.time_to_close,
        }
